{% set name = "ldap3" %}
{% set version = "2.9" %}
{% set sha256 = "18c3ee656a6775b9b0d60f7c6c5b094d878d1d90fc03d56731039f0a4b546a91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyasn1
  run:
    - python
    - pyasn1 >=0.1.8

test:
  imports:
    - ldap3

about:
  home: https://github.com/cannatag/ldap3
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER.txt
  summary: A strictly RFC 4510 conforming LDAP V3 pure Python client library
  doc_url: http://ldap3.readthedocs.io
  dev_url: https://github.com/cannatag/ldap3

extra:
  recipe-maintainers:
    - mcs07
